# Metadata
site_name: Vfll Docs
site_url: https://doku.vfll.de
site_author: Ulrich Kilian 

# Repository
repo_name: scienceuli/vflldoku
repo_url: https://github.com/scienceuli/vflldoku

use_directory_urls: true

# Navigation
# nav: 
#   - Home: index.md
#   - Profil: profiles.md
#   - Teams: teams.md
#   - Aufgaben: aufgaben.md
#   - Dokumente und Verzeichnisse: documents.md
#   - Nextcloud-Anbindung: nextcloud.md
#   - Umfragen: polls.md
#   - Meetings (BBB): bbb.md
#   - Meetings (Zoom): zoom.md

# Material for MkDocs
theme:
  language: de
  name: material
  custom_dir: docs/.overrides
  features:
    - search.suggest
    - search.highlight

markdown_extensions:
  - pymdownx.details
  - attr_list
  - md_in_html
  - toc:
      permalink: true
      title: Inhaltsverzeichnis

plugins:
  - pub-debugger
  - search
  - pub-obsidian
  - pub-minifier
  - glightbox

hooks:
  - hooks.py