attachments/Screenshot-Zoom-Meeting-Details.jpg:
  cached_file_name: 74e35163764a46e596bb511099affa67.jpg
  original_file_hash: e09ea89fa704f0a38f58b86dd050dff5
  original_file_path: attachments/Screenshot-Zoom-Meeting-Details.jpg
attachments/Zoom-Kalender-finden.jpg:
  cached_file_name: 6c6b5c0e7ed74d9ba2759b8c174a8dfc.jpg
  original_file_hash: 25a883668b2dfb45d6e3b3b3d408d808
  original_file_path: attachments/Zoom-Kalender-finden.jpg
attachments/Zoom-Meeting-anlegen1.jpg:
  cached_file_name: 6c9e8c7235234fc0b34bd19110d5efb9.jpg
  original_file_hash: 7762d47169a4c4f0474e1f68068e71dc
  original_file_path: attachments/Zoom-Meeting-anlegen1.jpg
attachments/Zoom-Meeting-anlegen2.jpg:
  cached_file_name: 98b707d60b15430d8750c3d3926b5a0b.jpg
  original_file_hash: fc31ef6eb2495f27b0bface3360a07bc
  original_file_path: attachments/Zoom-Meeting-anlegen2.jpg
